# web_server_setup/tasks/main.yml
---
- name: Install Web Server Package
  package:
    name: "{{ web_server_package }}"
    state: present

- name: Ensure Web Server is running and enabled
  service:
    name: "{{ web_server_service_name }}"
    state: started
    enabled: yes

- name: Create a basic virtual host
  template:
    src: "templates/{{ web_server_virtual_host_template }}"
    dest: "/etc/apache2/sites-available/basic_virtual_host.conf"

- name: Ensure Web Server is running and enabled
  service:
    name: "{{ web_server_service_name }}"
    state: reloaded
    enabled: yes